---
- name: launch dockerized wordpress instance
  docker_container:
    name: wordpress
    image: wordpress
    published_ports: 8080:80
    pull: true
    restart: true
    state: started
    env:
      WORDPRESS_DB_HOST: "{{ wordpress_db_host }}"
      WORDPRESS_DB_USER: "{{ wordpress_db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
